version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    entrypoint: /entrypoint.sh
    env_file:
     - ./.env
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/certs:/etc/letsencrypt:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 24h & wait $${!}; certbot renew; done;'"
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/html:/var/www/html

  certbot_init:
    image: certbot/certbot
    container_name: certbot_init
    env_file:
     - ./.env
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/html:/var/www/html
